<a href="https://colab.research.google.com/github/abakm/AL-ML_Assignment-1/blob/master/Assignment_04_Ensemble_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:
# import statements
import numpy as np
import pandas as pd
import statistics as st
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split, StratifiedGroupKFold
from sklearn.ensemble import VotingClassifier, BaggingClassifier, AdaBoostClassifier, GradientBoostingClassifier

In [90]:
# Read the dataset to the python environment.
df = pd.read_csv("./train_loan.csv")
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

### pre-processing steps.

In [91]:
# check for null values

df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [92]:
# Remove  rows with null values

df.dropna(inplace=True)
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
5               5417             4196.0       267.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
5               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[480 rows x 13 columns]

In [93]:
# Remove duplicate rows
df.drop_duplicates(inplace=True)
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
5    LP001011    Male     Yes          2      Graduate           Yes   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
5               5417             4196.0       267.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
5               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[480 rows x 13 columns]

In [94]:
# Remove unneccessary columns
df.drop(["Loan_ID"], axis=1, inplace=True)
df

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
1      Male     Yes          1      Graduate            No             4583   
2      Male     Yes          0      Graduate           Yes             3000   
3      Male     Yes          0  Not Graduate            No             2583   
4      Male      No          0      Graduate            No             6000   
5      Male     Yes          2      Graduate           Yes             5417   
..      ...     ...        ...           ...           ...              ...   
609  Female      No          0      Graduate            No             2900   
610    Male     Yes         3+      Graduate            No             4106   
611    Male     Yes          1      Graduate            No             8072   
612    Male     Yes          2      Graduate            No             7583   
613  Female      No          0      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
5               4196.0       267.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

    Property_Area Loan_Status  
1           Rural           N  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
5           Urban           Y  
..            ...         ...  
609         Rural           Y  
610         Rural           Y  
611         Urban           Y  
612         Urban           Y  
613     Semiurban           N  

[480 rows x 12 columns]

In [95]:

label_encoder = LabelEncoder()

# Apply Label Encoding to the 'Gender, Married, Loan_Status, Education, Self_Employed and Property_Area columns
df["Gender"] = label_encoder.fit_transform(df["Gender"])
df["Married"] = label_encoder.fit_transform(df["Married"])
df['Loan_Status'] = label_encoder.fit_transform(df['Loan_Status'])
df["Education"] = label_encoder.fit_transform(df["Education"])
df["Self_Employed"] = label_encoder.fit_transform(df["Self_Employed"])
df["Property_Area"] = label_encoder.fit_transform(df["Property_Area"])

df


Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
1         1        1          1          0              0             4583   
2         1        1          0          0              1             3000   
3         1        1          0          1              0             2583   
4         1        0          0          0              0             6000   
5         1        1          2          0              1             5417   
..      ...      ...        ...        ...            ...              ...   
609       0        0          0          0              0             2900   
610       1        1         3+          0              0             4106   
611       1        1          1          0              0             8072   
612       1        1          2          0              0             7583   
613       0        0          0          0              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
5               4196.0       267.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

     Property_Area  Loan_Status  
1                0            0  
2                2            1  
3                2            1  
4                2            1  
5                2            1  
..             ...          ...  
609              0            1  
610              0            1  
611              2            1  
612              2            1  
613              1            0  

[480 rows x 12 columns]

In [96]:
# check for the values in the Dependents as its does have 3+ as values as its not a number so that we will preprocess them
df['Dependents'].unique()

array(['1', '0', '2', '3+'], dtype=object)

In [97]:
# Replace 3+ with 3

df['Dependents'] = pd.to_numeric(df['Dependents'].replace('3+', '3'), errors='coerce')
df['Dependents'] = df['Dependents'].astype(int)
df

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
1         1        1           1          0              0             4583   
2         1        1           0          0              1             3000   
3         1        1           0          1              0             2583   
4         1        0           0          0              0             6000   
5         1        1           2          0              1             5417   
..      ...      ...         ...        ...            ...              ...   
609       0        0           0          0              0             2900   
610       1        1           3          0              0             4106   
611       1        1           1          0              0             8072   
612       1        1           2          0              0             7583   
613       0        0           0          0              1             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
5               4196.0       267.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

     Property_Area  Loan_Status  
1                0            0  
2                2            1  
3                2            1  
4                2            1  
5                2            1  
..             ...          ...  
609              0            1  
610              0            1  
611              2            1  
612              2            1  
613              1            0  

[480 rows x 12 columns]

#Perform different Ensemble Learning techniques in the given dataset.

In [98]:
# split dataset
x =df.drop("Loan_Status", axis=1)
y = df["Loan_Status"]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [99]:
# create models



knc = KNeighborsClassifier()
dtc = DecisionTreeClassifier(random_state=1)

In [100]:
# Train Models
knc.fit(x_train, y_train)
dtc.fit(x_train, y_train)

DecisionTreeClassifier(random_state=1)

In [101]:
# Predict the models
print("KNN",knc.predict(x_test))
print("DT",dtc.predict(x_test))

KNN [1 1 1 1 1 0 1 1 1 1 1 0 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 1 0 1 1 1 0 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0]
DT [1 1 1 0 1 0 1 1 1 0 0 1 1 1 1 1 0 0 1 0 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1
 1 0 0 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0
 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 1 1]


### Esemble

In [102]:
final_predictions = np.array([])
for i in range(0, len(x_test)):
  final_predictions =  np.append(final_predictions, st.mode([knc.predict(x_test)[i], dtc.predict(x_test)[i]]))

final_predictions


array([1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.,
       1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0.])

### Max voting

In [103]:
# Create models , combine model predictions
knc = KNeighborsClassifier()
dtc = DecisionTreeClassifier(random_state=1)
vc = VotingClassifier(estimators=[('KNC', knc), ('DTC', dtc)], voting='hard')
vc.fit(x_train, y_train)
vc.score(x_test, y_test)

0.6979166666666666

In [104]:
### predict the model

vc.predict(x_test)

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0])

### Average Voting

In [105]:
# create model
knc_avg = KNeighborsClassifier()
dtc_avg = DecisionTreeClassifier(random_state=1)

In [106]:
# fit the models
knc_avg.fit(x_train, y_train)
dtc_avg.fit(x_train, y_train)

DecisionTreeClassifier(random_state=1)

In [107]:
# predict the models
knc_avg_predict  = knc_avg.predict_proba(x_test)
dtc_avg_predict = dtc_avg.predict_proba(x_test)

In [108]:
# Final combined prediction
final_avg_prediction = (knc_avg_predict + dtc_avg_predict )/3
final_avg_prediction

array([[0.13333333, 0.53333333],
       [0.06666667, 0.6       ],
       [0.13333333, 0.53333333],
       [0.33333333, 0.33333333],
       [0.13333333, 0.53333333],
       [0.6       , 0.06666667],
       [0.13333333, 0.53333333],
       [0.13333333, 0.53333333],
       [0.06666667, 0.6       ],
       [0.46666667, 0.2       ],
       [0.4       , 0.26666667],
       [0.2       , 0.46666667],
       [0.        , 0.66666667],
       [0.26666667, 0.4       ],
       [0.2       , 0.46666667],
       [0.        , 0.66666667],
       [0.4       , 0.26666667],
       [0.53333333, 0.13333333],
       [0.06666667, 0.6       ],
       [0.4       , 0.26666667],
       [0.13333333, 0.53333333],
       [0.        , 0.66666667],
       [0.13333333, 0.53333333],
       [0.4       , 0.26666667],
       [0.        , 0.66666667],
       [0.13333333, 0.53333333],
       [0.06666667, 0.6       ],
       [0.46666667, 0.2       ],
       [0.06666667, 0.6       ],
       [0.33333333, 0.33333333],
       [0.

### Weighted Averaging

In [109]:
# create model
knc_wg_avg = KNeighborsClassifier()
dtc_wg_avg = DecisionTreeClassifier(random_state=1)

In [110]:
# fit the models
knc_wg_avg.fit(x_train, y_train)
dtc_wg_avg.fit(x_train, y_train)

DecisionTreeClassifier(random_state=1)

In [111]:
final_avg_predictions = (knc_avg_predict*0.3 + dtc_avg_predict*0.3)
final_avg_predictions

array([[0.12, 0.48],
       [0.06, 0.54],
       [0.12, 0.48],
       [0.3 , 0.3 ],
       [0.12, 0.48],
       [0.54, 0.06],
       [0.12, 0.48],
       [0.12, 0.48],
       [0.06, 0.54],
       [0.42, 0.18],
       [0.36, 0.24],
       [0.18, 0.42],
       [0.  , 0.6 ],
       [0.24, 0.36],
       [0.18, 0.42],
       [0.  , 0.6 ],
       [0.36, 0.24],
       [0.48, 0.12],
       [0.06, 0.54],
       [0.36, 0.24],
       [0.12, 0.48],
       [0.  , 0.6 ],
       [0.12, 0.48],
       [0.36, 0.24],
       [0.  , 0.6 ],
       [0.12, 0.48],
       [0.06, 0.54],
       [0.42, 0.18],
       [0.06, 0.54],
       [0.3 , 0.3 ],
       [0.12, 0.48],
       [0.06, 0.54],
       [0.  , 0.6 ],
       [0.  , 0.6 ],
       [0.12, 0.48],
       [0.  , 0.6 ],
       [0.  , 0.6 ],
       [0.06, 0.54],
       [0.36, 0.24],
       [0.3 , 0.3 ],
       [0.06, 0.54],
       [0.12, 0.48],
       [0.48, 0.12],
       [0.36, 0.24],
       [0.12, 0.48],
       [0.42, 0.18],
       [0.48, 0.12],
       [0.06,

# Bagging

In [112]:
# create the base models

tree = DecisionTreeClassifier(max_depth=3, random_state=42)



In [113]:
# create model
bagging_clf = BaggingClassifier(estimator=tree, n_estimators=100, max_samples=50, random_state=42, bootstrap=True)

In [114]:
# fit the model
bagging_clf.fit(x_train, y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(max_depth=3,
                                                   random_state=42),
                  max_samples=50, n_estimators=100, random_state=42)

In [115]:
# Predict the model

bagging_predict = bagging_clf.predict(x_test)
#

In [116]:
# accuracy
print(accuracy_score(y_train, bagging_clf.predict(x_train)))
print(bagging_clf.score(x_train, y_train))
print(bagging_clf.score(x_test, y_test))

0.8046875
0.8046875
0.8229166666666666


# Boosting
#### using Adboost

In [117]:
# create model
adb = AdaBoostClassifier(n_estimators=100, random_state=42)

In [118]:
# Fit the model
adb.fit(x_train, y_train)

AdaBoostClassifier(n_estimators=100, random_state=42)

In [119]:
# Predict the model
adb_predict = adb.predict(x_test)
adb_predict

array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1])

In [120]:
# Score
print(adb.score(x_train, y_train))
print(adb.score(x_test, y_test))


0.8229166666666666
0.8125


####  Using GradientBoost

In [121]:
# create the model
gdb = GradientBoostingClassifier(learning_rate=0.01, n_estimators=5, random_state=42)

In [122]:
# Fit the model
gdb.fit(x_train, y_train)

GradientBoostingClassifier(learning_rate=0.01, n_estimators=5, random_state=42)

In [123]:
gdb_predict = gdb.predict(x_test)
gdb_predict

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [124]:
# Score
print(gdb.score(x_train, y_train))
print(gdb.score(x_test, y_test))

0.6875
0.7083333333333334


# Stacking

In [125]:
from sklearn.model_selection import StratifiedKFold

In [126]:
# Train first-level models and create meta-features
def stacking(model, train, y, test, n_fold):
  folds = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state=1)
  train_meta_features, test_meta_features = np.zeros((train.shape[0], 1)), np.zeros((test.shape[0], 1))
  for train_idx, test_idx in folds.split(train, y):
    x_train, x_test = train.iloc[train_idx], train.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
    model.fit(x_train, y_train)
    predict = model.predict(x_test)
    test_predict = model.predict(test)
    train_meta_features[test_idx, 0] = predict
    test_meta_features[:, 0] += test_predict
  test_meta_features /= n_fold
  return train_meta_features, test_meta_features

### create two base models

In [127]:
# create decision tree model
tree = DecisionTreeClassifier(random_state=1)
train_predict1, test_predict1 = stacking(model=tree, train=x_train, y=y_train, test=x_test, n_fold=10)
train_predict1 = pd.DataFrame(train_predict1)
test_predic1 = pd.DataFrame(test_predict1)

In [128]:
# create KNN model
tree = KNeighborsClassifier()
train_predict2, test_predict2 = stacking(model=tree, train=x_train, y=y_train, test=x_test, n_fold=10)
train_predict2 = pd.DataFrame(train_predict2)
test_predict2 = pd.DataFrame(test_predict2)

### create meta model

In [129]:
# create meta model ,fit the model and predict
meta_df = pd.concat([train_predict1, train_predict2], axis=1)
meta_df_test = pd.concat([test_predic1, test_predict2], axis=1)
lr = LogisticRegression()
lr.fit(meta_df, y_train)
lr.predict(meta_df_test)

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [130]:
# score
lr.score(meta_df, y_train)

0.6901041666666666

# Hyperparameter tuning

### using GridSearchCV

In [131]:
parameters = {
    'n_estimators': [50, 100, 200],
    'max_depth': [10, 50, 60],
    "criterion": ["gini", "entropy"],
}

grid_search = GridSearchCV(RandomForestClassifier(), parameters, cv=5, scoring="accuracy", verbose=1, n_jobs=1)
grid_search.fit(x, y)

best_params = grid_search.best_params_
best_score = grid_search.best_score_

print("Best Parameters:", best_params)
print("Best Score:", best_score)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
Best Parameters: {'criterion': 'gini', 'max_depth': 10, 'n_estimators': 200}
Best Score: 0.8104166666666666


### using RandomizedSearchCV

In [132]:
random_search = RandomizedSearchCV(RandomForestClassifier(), parameters, n_iter=18, cv=5, scoring="accuracy", verbose=1, n_jobs=1)
random_search.fit(x, y)

best_params = random_search.best_params_
best_score = random_search.best_score_

print("Best Parameters:", best_params)
print("Best Score:", best_score)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
Best Parameters: {'n_estimators': 50, 'max_depth': 10, 'criterion': 'gini'}
Best Score: 0.8125
